var averages = {
  averages: {
    communes: {},
    provinces: {},
    regions: {}
  },
  min: {
    communes: {},
    provinces: {},
    regions: {}
  },
  max: {
    communes: {},
    provinces: {},
    regions: {}
  },
  colors: {
    communes: {},
    provinces: {},
    regions: {}
  },
  maps: {
    communes: {},
    provinces: {
      Aisen: "Aysén",
      Antartica_Chilena: "Antártica Chilena",
      Antofagasta: "Antofagasta",
      Arauco: "Arauco",
      Arica: "Arica",
      Biobio: "Biobío",
      Cachapoal: "Cachapoal",
      Capitan_Prat: "Capitán Prat",
      Cardenal_Caro: "Cardenal Caro",
      Cauquenes: "Cauquenes",
      Cautin: "Cautín",
      Chacabuco: "Chacabuco",
      Chanaral: "Chañaral",
      Chiloe: "Chiloé",
      Choapa: "Choapa",
      Coihaique: "Coyhaique",
      Colchagua: "Colchagua",
      Concepcion: "Concepción",
      Copiapo: "Copiapó",
      Cordillera: "Cordillera",
      Curico: "Curicó",
      Diguillin:"Diguillín",
      El_Loa: "El Loa",
      Elqui: "Elqui",
      General_Carrera: "General Carrera",
      Huasco: "Huasco",
      Iquique: "Iquique",
      Itata:"Itata",
      Limari: "Limarí",
      Linares: "Linares",
      Llanquihue: "Llanquihue",
      Los_Andes: "Los Andes",
      Magallanes: "Magallanes",
      Maipo: "Maipo",
      Malleco: "Malleco",
      Marga_Marga: "Marga Marga",
      Melipilla: "Melipilla",
      Osorno: "Osorno",
      Palena: "Palena",
      Parinacota: "Parinacota",
      Petorca: "Petorca",
      Punilla: "Punilla",
      Quillota: "Quillota",
      Ranco: "Ranco",
      San_Antonio: "San Antonio",
      San_Felipe_de_Aconcagua: "San Felipe de Aconcagua",
      Santiago: "Santiago",
      Talagante: "Talagante",
      Talca: "Talca",
      Tamarugal: "Tamarugal",
      Tierra_del_Fuego: "Tierra del Fuego",
      Tocopilla: "Tocopilla",
      Ultima_Esperanza: "Última Esperanza",
      Valdivia: "Valdivia",
      Valparaiso: "Valparaíso"
    },
    regions: {
      Arica_Parinacota: "Arica y Parinacota",
      Tarapaca: "Tarapacá",
      Antofagasta: "Antofagasta",
      Atacama: "Atacama",
      Coquimbo: "Coquimbo",
      Valparaiso: "Valparaíso",
      Metropolitana: "Metropolitana",
      OHiggins: "Libertador General Bernardo O'Higgins",
      Maule: "Maule",
      Nuble: "Ñuble",
      Biobio: "Biobío",
      Araucania: "La Araucanía",
      Los_Rios: "Los Ríos",
      Los_Lagos: "Los Lagos",
      Aisen: "Aysén del General Carlos Ibáñez del Campo",
      Magallanes: "Magallanes y de la Antártica Chilena"
    }
  }
};

module.exports = averages;